/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tungds.jframe;

import com.tungds.commons.ManagerMenu;
import com.tungds.jforms.CustomerFormEditor;
import com.tungds.models.Customer;
import com.tungds.models.Entity;
import com.tungds.models.Product;
import javax.swing.JOptionPane;

/**
 *
 * @author anhle
 */
public class CustomerPanelManager extends javax.swing.JPanel {

    public Entity entities;
    
    private String[] columns =  new String [] {
                "Code", "Name", "Phone"
            };
    
    public CustomerPanelManager(Entity entities) {
        initComponents();
        this.entities = entities;
        loadDataToTable();
    }
    
    public void loadDataToTable() {
        
        if(entities.customers.size() == 0)
            return;
        
        Object[][] arrData = new Object[entities.customers.size()][columns.length];
        
        for(int i = 0 ;i < entities.customers.size();i++){
            Customer product = entities.customers.get(i);
            arrData[i][0] = product.ccode;
            arrData[i][1] = product.cname;
            arrData[i][2] = product.phone;
        }
        
         jTable1.setModel(new javax.swing.table.DefaultTableModel(
            arrData,
           columns
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btAdd = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        txtSreachByCcode = new javax.swing.JTextField();
        btSreachByCcode = new javax.swing.JButton();
        btSreachByCcode1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btSort = new javax.swing.JButton();

        btAdd.setText("Add");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btEdit.setText("Edit");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });

        txtSreachByCcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSreachByCcodeActionPerformed(evt);
            }
        });

        btSreachByCcode.setText("Sreach by Code");
        btSreachByCcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSreachByCcodeActionPerformed(evt);
            }
        });

        btSreachByCcode1.setText("Delete by Code");
        btSreachByCcode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSreachByCcode1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Code", "Name", "Phone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        btSort.setText("Sort by Code");
        btSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSort, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSreachByCcode, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSreachByCcode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSreachByCcode1)))
                .addGap(0, 6, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEdit)
                    .addComponent(btAdd)
                    .addComponent(btSort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSreachByCcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btSreachByCcode)
                        .addComponent(btSreachByCcode1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        // TODO add your handling code here:
        CustomerFormEditor editor = new CustomerFormEditor(this);
        editor.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        editor.setVisible(true);
    }//GEN-LAST:event_btAddActionPerformed

    private void txtSreachByCcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSreachByCcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSreachByCcodeActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        CustomerFormEditor editor = new CustomerFormEditor(this, entities.customers.get(index));
        editor.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        editor.setVisible(true);
    }//GEN-LAST:event_btEditActionPerformed

    private void btSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSortActionPerformed
        ManagerMenu.quicksort(entities.products);
        loadDataToTable();
        JOptionPane.showMessageDialog(this,"success");
    }//GEN-LAST:event_btSortActionPerformed

    private void btSreachByCcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSreachByCcodeActionPerformed
        // TODO add your handling code here:
        
        String code = txtSreachByCcode.getText();
        int result = ManagerMenu.binarysreach(entities.customers, new Customer(code));
        if(result != -1){
             jTable1.getSelectionModel().setSelectionInterval(0, result);
            JOptionPane.showMessageDialog(this,"success");
        }else{
            JOptionPane.showMessageDialog(this,"can't find production");
        }
    }//GEN-LAST:event_btSreachByCcodeActionPerformed

    private void btSreachByCcode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSreachByCcode1ActionPerformed
       String code = txtSreachByCcode.getText();
        int result = ManagerMenu.binarysreach(entities.customers, new Customer(code));
        if(result != -1){
            entities.customers.remove(result);
            JOptionPane.showMessageDialog(this,"success");
        }else{
            JOptionPane.showMessageDialog(this,"can't find production");
        }
    }//GEN-LAST:event_btSreachByCcode1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btSort;
    private javax.swing.JButton btSreachByCcode;
    private javax.swing.JButton btSreachByCcode1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtSreachByCcode;
    // End of variables declaration//GEN-END:variables

   
}
