/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tungds.jforms;

import com.tungds.commons.ManagerMenu;
import com.tungds.enums.TypeEdit;
import com.tungds.models.Ordering;
import com.tungds.jframe.OrderingPanelManager;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author TungDS
 */
public class OrderingFormEditor extends javax.swing.JFrame {

    private TypeEdit editorType;
    private Ordering ordering;
    OrderingPanelManager orderingPanelManager;

    public OrderingFormEditor(OrderingPanelManager orderingPanelManager) {
        initComponents();

        editorType = TypeEdit.CREATE;
        this.orderingPanelManager = orderingPanelManager;

        initDataAndFillComponent();
    }

    public OrderingFormEditor(OrderingPanelManager orderingPanelManager, Ordering ordering) {
        initComponents();

        editorType = TypeEdit.EDIT;
        this.ordering = ordering;

        this.orderingPanelManager = orderingPanelManager;

        initDataAndFillComponent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbQuantity = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        lbCustomer = new javax.swing.JLabel();
        lbProduct = new javax.swing.JLabel();
        cbProduct = new javax.swing.JComboBox<>();
        cbCustomer = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbQuantity.setText("Quantity :");

        jLabel1.setText("Ordering Editor");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lbCustomer.setText("Customer :");

        lbProduct.setText("Product :");

        cbProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbCustomer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbQuantity)
                    .addComponent(lbCustomer)
                    .addComponent(lbProduct))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnSave))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtQuantity)
                        .addComponent(jLabel1)
                        .addComponent(cbCustomer, 0, 180, Short.MAX_VALUE)
                        .addComponent(cbProduct, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbProduct))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCustomer)
                    .addComponent(cbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuantity)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSave)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        ordering.pcode = orderingPanelManager.entities.products.get(cbProduct.getSelectedIndex()).pcode;
        ordering.ccode = orderingPanelManager.entities.customers.get(cbCustomer.getSelectedIndex()).ccode;
        ordering.quantity = Integer.parseInt(txtQuantity.getText());
//
        if (editorType == TypeEdit.CREATE) {
            orderingPanelManager.entities.orderings.add(ordering);
        }
        this.dispose();
        orderingPanelManager.loadDataToTable();
    }//GEN-LAST:event_btnSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbCustomer;
    private javax.swing.JComboBox<String> cbProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbCustomer;
    private javax.swing.JLabel lbProduct;
    private javax.swing.JLabel lbQuantity;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables

    private void initDataAndFillComponent() {

        String[] arrProductName = new String[orderingPanelManager.entities.products.size()];
        for (int i = 0; i < orderingPanelManager.entities.products.size(); i++) {
            arrProductName[i] = orderingPanelManager.entities.products.get(i).pname;
        }
        cbProduct.setModel(new DefaultComboBoxModel<String>(arrProductName));

        String[] arrCustomerName = new String[orderingPanelManager.entities.customers.size()];
        for (int i = 0; i < orderingPanelManager.entities.customers.size(); i++) {
            arrCustomerName[i] = orderingPanelManager.entities.customers.get(i).cname;
        }
        cbCustomer.setModel(new DefaultComboBoxModel<String>(arrCustomerName));

        if (editorType == TypeEdit.CREATE) {
            ordering = new Ordering();

            if ((orderingPanelManager.entities.products.size()) > 0) {
                cbProduct.setSelectedIndex(0);
            }

            if ((orderingPanelManager.entities.customers.size()) > 0) {
                cbCustomer.setSelectedIndex(0);
            }

        } else {

            cbProduct.setSelectedIndex(ManagerMenu.getIndexProductByCode(orderingPanelManager.entities.products, ordering.pcode));
            cbCustomer.setSelectedIndex(ManagerMenu.getIndexCustomerByCode(orderingPanelManager.entities.customers, ordering.ccode));

        }

        txtQuantity.setText("" + ordering.quantity);
    }
}
